### PR TITLE
[HOLD] v1 refactoring to baseline

### PR DESCRIPTION
**Pull request by jkodumal**
This preps the ruby client for v2 updates by bringing ruby in line with the architecture of the other SDKs

### CODE REVIEW

**Comment by drichelson** [comment]
y u no test pass? should I wait to look at this?

**Comment by jkodumal** [comment]
It's probably worth waiting until I update the tests.

**Comment by jkodumal** [comment]
Slight change in plans: I'll get the tests up and going against the `jko/v2-evaluation` branch.

**Comment by jkodumal** [comment]
Obviated by #67

**Pull request closed without merging**
